name: student_project

channels:
  - conda-forge

dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- statsmodels
- r-base
- r-tidyverse
- r-essentials
- r-irkernel
- r-largeList
- r-mass
- pip
- pip:


