#' This function extracts the measuring interval from a functional observation.
#'
#'@param func_obs: a list, that contains two vectors of identical length: args and vals
#'
#'@return A vector of two elements, the start and endpoints of the measuring interval
#'@export
measuring_int <- function(func_obs){
  # Extract Interval from functional observation
  interval <-  c(min(func_obs$args), max(func_obs$args))
  # return interval vector
  return(interval)                     
}

#' This function extracts the measuring interval from a set of functional observations.
#'
#'@param func_dat: a list, that contains two vectors of identical length: args and vals
#'
#'@return A list of vectors containing two elements, the start and endpoints of the measuring intervals
#'@export
measuring_int_list <- function(func_dat){
  # Extract Intervals from functional observation
  intervals_list <-  map(.x = func_dat,
                         .f = measuring_int)
  # return list of interval vectors
  return(intervals_list)                     
}

#' This function is a wrapper around measuring_int_list and combines the intervals
#' into a length(func_dat)x2 matrix
#'
#'@param func_dat: a list, that contains two vectors of identical length: args and vals
#'
#'@return A list of vectors containing two elements, the start and endpoints of the measuring intervals
#'@export
measuring_int_mat <- function(func_dat){
  # Extract Intervals from functional observation
  intervals_list <- measuring_int_list(func_dat)
  # combine into matrix
  intervals_matrix <- matrix(data = unlist(intervals_list), 
                             nrow = length(func_dat), ncol = 2,
                             byrow = TRUE)
  # return matrix
  return(intervals_matrix)                     
}

#' Given a matrix of measuring intervals as generated by measuring_int_mat
#' this function extracts the unique intervals in the data set and returns
#' a reduced matrix containing only the unique intervals
#'
#'@param interval_matrix: A matrix with 2 columns containing in its rows
#' the measuring intervals of the observations
#'
#'@return A matrix containing the unique measuring intervals found 
#' in the data set
#'@export
unique_intervals <- function(interval_matrix){
  
  # for finding unique entries transforming to a list is easier
  interval_list <- map(.x = seq_len(nrow(interval_matrix)), 
                       .f = function(i) interval_matrix[i,])
  
  # find unique entries                             
  unique_intervals <- unique(interval_list)
  
  # combine into matrix again                         
  unique_matrix <- matrix(data = unlist(unique_intervals), 
                          nrow = length(unique_intervals),
                          byrow = TRUE)
  
  # return matrix where each row contains the beginning and end points of a unique measuring interval
  # from the data set
  return(unique_matrix)                         
}