# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hM_depth <- function(valueMatrix, grid) {
    .Call(`_OutDetectR_hM_depth`, valueMatrix, grid)
}

grid_approx_obs <- function(args, vals, grid) {
    .Call(`_OutDetectR_grid_approx_obs`, args, vals, grid)
}

