# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grid_approx_obs <- function(args, vals, grid) {
    .Call(`_OSEproject_grid_approx_obs`, args, vals, grid)
}

hM_depth <- function(valueMatrix, grid) {
    .Call(`_OSEproject_hM_depth`, valueMatrix, grid)
}

rcpp_hello_world <- function() {
    .Call(`_OSEproject_rcpp_hello_world`)
}

