// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hM_depth
NumericVector hM_depth(NumericMatrix valueMatrix, NumericVector grid);
RcppExport SEXP _OutDetectR_hM_depth(SEXP valueMatrixSEXP, SEXP gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type valueMatrix(valueMatrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid(gridSEXP);
    rcpp_result_gen = Rcpp::wrap(hM_depth(valueMatrix, grid));
    return rcpp_result_gen;
END_RCPP
}
// grid_approx_obs
NumericVector grid_approx_obs(NumericVector args, NumericVector vals, NumericVector grid);
RcppExport SEXP _OutDetectR_grid_approx_obs(SEXP argsSEXP, SEXP valsSEXP, SEXP gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type args(argsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type grid(gridSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_approx_obs(args, vals, grid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OutDetectR_hM_depth", (DL_FUNC) &_OutDetectR_hM_depth, 2},
    {"_OutDetectR_grid_approx_obs", (DL_FUNC) &_OutDetectR_grid_approx_obs, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_OutDetectR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
