name: Continuous Integration

on: [push]

jobs:
  py_setup:
  
    name: 'Setup Python'

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Miniconda Setup
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: student_project
        environment-file: environment.yml
        python-version: 3.6
        auto-activate-base: false   
    - name: path export and IRkernel
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        conda activate student_project 
        R -e "IRkernel::installspec()"
        R -e "install.packages('~/Code/OutDetectR_1.0.tar.gz', repos = NULL, type = 'source')"
        jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=120 Project_Main.ipynb
      
