name: Continuous Integration

on: [push]

jobs:
  py_setup:
  
    name: 'Setup Python'

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: student_project
        environment-file: environment.yml
        python-version: 3.6
        auto-activate-base: false   
        
  R_setup:
    needs: py_setup
    
    name: 'Setup R environment'
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: r-lib/actions/setup-r@v1
      with:
         r-version: '4.1.0'
     
    - name: Cache Renv packages
      uses: actions/cache@v2
      with:
        path: renv/
        key: r-${{ hashFiles('renv.lock') }}
        restore-keys: r-
        
    - name: Install packages
      run: |
         R -e 'install.packages("renv")'
         R -e 'renv::restore()'
            
    - name: Initialize IR_kernel
      shell: Rscript {0}
      run: IRkernel::installspec()
       
  build:
    needs: [py_setup, R_setup]
    
    runs-on: ubuntu-latest
    steps:
    - name: execute notebooks
      shell: bash -l {0}
      run: |
         export PATH="$PATH:/usr/share/miniconda/bin"
         source .envrc
         jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=120 *.ipynb
      
