name: Continuous Integration

on: [push]

jobs:
  py_setup:
  
    name: 'Setup Python'

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: student_project
        environment-file: environment.yml
        python-version: 3.6
        auto-activate-base: false   
    - run: |
        conda info --envs
        export PATH="$PATH:/usr/share/miniconda/bin"
        
  R_setup:
    
    name: 'Setup R environment'
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: r-lib/actions/setup-r@v1
      with:
         r-version: '4.1.0'

    - name: Install Packages
      shell: Rscript {0}
      run: |
        install.packages("MASS")
        install.packages("tidyverse")
        install.packages("shiny")
        install.packages("largeList")
        install.packages("parallel")
        install.packages("Rcpp")
        install.packages("IRkernel")
    
  ir_kernel:
  
    needs: [py_setup, R_setup]
    name: 'Initialize IR Kernel'
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Initialize IR Kernel
      run: R -e "IRkernel::installspec()"
      
  build:
    needs: [py_setup, R_setup, ir_kernel]
    
    runs-on: ubuntu-latest
    steps:
    - name: execute notebooks
      shell: bash -l {0}
      run: jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=120 *.ipynb
      
