name: Continuous Integration

on: [push]

jobs:
  py_setup:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: student_project
        environment-file: environment.yml
        python-version: 3.6
        auto-activate-base: false   
        
  R_setup:
    needs: py_setup
    runs-on: ubuntu-latest
    
    name: 'Setup R environment'
    
    env:
        RENV_PATHS_ROOT: renv
    
    steps:
    - uses: r-lib/actions/setup-r@v1
      with:
         r-version: '4.1.0'
         
    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: |
         while read -r cmd
         do
           eval sudo $cmd
         done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
       
    - name: Install dependencies
      shell: Rscript {0}
      run: |
         remotes::install_deps(dependencies = TRUE)
         remotes::install_cran("rcmdcheck")
      
    - name: Cache packages
      uses: actions/cache@v1
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
            ${{ runner.os }}-renv-

    - name: Restore packages
      shell: Rscript {0}
      run: |
         if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
         renv::restore()
            
    - name: Restore packages
      shell: Rscript {0}
      run: IRkernel::installspec()
       
  build:
    needs: [py_setup, R_setup]
    
    runs-on: ubuntu-latest
    steps:
    - name: execute notebooks
      shell: bash -l {0}
      run: |
         export PATH="$PATH:/usr/share/miniconda/bin"
         source .envrc
         jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=120 *.ipynb
      
