name: Continuous Integration

on: [push]

jobs:
  py_setup:
  
    name: 'Setup Python'

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: student_project
        environment-file: environment.yml
        python-version: 3.6
        auto-activate-base: false   
    - run: |
        conda info --envs
        export PATH="$PATH:/usr/share/miniconda/bin"
        
  R_setup:
    
    name: 'Setup R environment'
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: r-lib/actions/setup-r@v1
      with:
         r-version: '4.1.0'

    - name: Install Packages
      run: | 
        R -e "install.packages("IRkernel")"
        R -e "IRkernel::installspec()"
        
  IR_setup:
  
    needs: [py_setup, R_setup]
    
    name: 'Setup IR Kernel'
    
    runs-on: ubuntu-latest
    
    steps:
    - run: R -e "IRkernel::installspec()"
      
  build:
    needs: [py_setup, R_setup, IR_setup]
    
    runs-on: ubuntu-latest
    steps:
    - name: execute notebooks
      shell: bash -l {0}
      run: jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=120 *.ipynb
      
