name: Continuous Integration

on: [push]

jobs:
  py_setup:
  
    name: 'Setup Python'

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: student_project
        environment-file: environment.yml
        python-version: 3.6
        auto-activate-base: false   
    - run: |
        conda info --envs
        conda activate student_project
        export PATH="$PATH:/usr/share/miniconda/bin"
        R -e "IRkernel::installspec()"
  build:
    needs: [py_setup]
    
    runs-on: ubuntu-latest
    steps:
    - name: execute notebooks
      shell: bash -l {0}
      run: |
        conda activate student_project
        jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=120 *.ipynb
      
